### ISSUE TITLE
Catalogue database error

### ISSUE THREAD

**Issue by vitormsilva** [reTHINK-project/dev-catalogue#30]
Hi @Endebert,

I have this error when i start the catalogue, [catalogue-database-ptinovacao.txt](https://github.com/reTHINK-project/dev-catalogue/files/297953/catalogue-database-ptinovacao.txt)

I don't know if I'm doing something wrong..

I'm using the this [database](https://github.com/reTHINK-project/dev-catalogue/tree/master/docker/catalogue-database-reTHINKdefault), i don't know if is related with the information added to the header, example [runtime sourceCode.js](https://github.com/reTHINK-project/dev-catalogue/blob/master/docker/catalogue-database-reTHINKdefault/catalogue_objects/runtime/Runtime/sourceCode.js)

I'm using the docker-compose to startup all the services, check [here](https://github.com/reTHINK-project/testbeds/tree/master/nodes/PT-node)

Can you help me?

Thanks

**Comment by Endebert** [comment]
Hmm it seems to be a problem related to the description.json of the runtime, could you please double-check its content, maybe you accidentally deleted a symbol inside of it, or something like that? The file in the repository seems fine. It's definitely unrelated to the sourceCode.js.

The error is a MalformedJsonException and "protocolCapabilities" is the only clue. I believe the description.json of the runtime is the only file that contains it.

I don't have access to the docker-compose stuff you linked, but if possible, could you try running the database with the new "-v" option? That would give us more verbose logging and might help finding the root of the problem.

**Comment by vitormsilva** [comment]
I did an experiment, build the same runtime, in own database-ptinovacao.. and it works well, i don't know if this can gave you a clue to discover the problem.. 

I have the log with "-v" option [docker-compose.yml.txt](https://github.com/reTHINK-project/dev-catalogue/files/300140/docker-compose.txt)
I have my docker-compose.yml [here](https://github.com/reTHINK-project/dev-catalogue/files/300121/docker-compose.txt)


Can you run the [default catalogue database](https://github.com/reTHINK-project/dev-catalogue/tree/master/docker/catalogue-database-reTHINKdefault) in your local machine?

**Comment by Endebert** [comment]
I have tried it and got no errors. However, [I extended my code to print the contents of the file if parsing failed](https://github.com/reTHINK-project/dev-catalogue/commit/ac1936131a3d6989cc4a3173d31655474a99682a). I don't know how long docker needs to update the docker images, but please do a `docker pull rethink/catalogue-database` and try building the image of catalogue-database-reTHINKdefault again (probably best to use the `--no-cache` flag).

If you did everything correctly, and the error occurs again, the log should look something like this:
```
2016-06-07 11:08:24,712 E CatalogueDatabase  Parsing ./catalogue_objects/runtime/FirstRuntime/description.json failed!
 com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected ':' at line 11 column 27 path $.protocolCapabilities
	at com.google.gson.internal.Streams.parse(Streams.java:60) ~[rethink-catalogue-database-1.1.0-jar-with-dependencies.jar:?]
	at com.google.gson.JsonParser.parse(JsonParser.java:84) ~[rethink-catalogue-database-1.1.0-jar-with-dependencies.jar:?]
	at com.google.gson.JsonParser.parse(JsonParser.java:59) ~[rethink-catalogue-database-1.1.0-jar-with-dependencies.jar:?]
	at eu.rethink.catalogue.database.CatalogueDatabase.parseJson(CatalogueDatabase.java:386) ~[rethink-catalogue-database-1.1.0-jar-with-dependencies.jar:?]
	at eu.rethink.catalogue.database.CatalogueDatabase.parseObjects(CatalogueDatabase.java:421) [rethink-catalogue-database-1.1.0-jar-with-dependencies.jar:?]
	at eu.rethink.catalogue.database.CatalogueDatabase.start(CatalogueDatabase.java:318) [rethink-catalogue-database-1.1.0-jar-with-dependencies.jar:?]
	at eu.rethink.catalogue.database.CatalogueDatabase.main(CatalogueDatabase.java:267) [rethink-catalogue-database-1.1.0-jar-with-dependencies.jar:?]
Caused by: com.google.gson.stream.MalformedJsonException: Expected ':' at line 11 column 27 path $.protocolCapabilities
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1567) ~[rethink-catalogue-database-1.1.0-jar-with-dependencies.jar:?]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:534) ~[rethink-catalogue-database-1.1.0-jar-with-dependencies.jar:?]
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:429) ~[rethink-catalogue-database-1.1.0-jar-with-dependencies.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:720) ~[rethink-catalogue-database-1.1.0-jar-with-dependencies.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:743) ~[rethink-catalogue-database-1.1.0-jar-with-dependencies.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:718) ~[rethink-catalogue-database-1.1.0-jar-with-dependencies.jar:?]
	at com.google.gson.internal.Streams.parse(Streams.java:48) ~[rethink-catalogue-database-1.1.0-jar-with-dependencies.jar:?]
	... 6 more
2016-06-07 11:08:24,715 E CatalogueDatabase  Contents of file ./catalogue_objects/runtime/FirstRuntime/description.json:
2016-06-07 11:08:24,715 E CatalogueDatabase  {
2016-06-07 11:08:24,716 E CatalogueDatabase    "cguid": "49816518489165",
2016-06-07 11:08:24,716 E CatalogueDatabase    "runtimeType": "browser",
2016-06-07 11:08:24,716 E CatalogueDatabase    "version": "1.0",
2016-06-07 11:08:24,716 E CatalogueDatabase    "objectName": "FirstRuntime",
2016-06-07 11:08:24,716 E CatalogueDatabase    "description": "This is a hyperty runtime descriptor",
2016-06-07 11:08:24,716 E CatalogueDatabase    "language": "Javascript ECMA6",
2016-06-07 11:08:24,716 E CatalogueDatabase    "hypertyCapabilities": {
2016-06-07 11:08:24,716 E CatalogueDatabase      "mic": false
2016-06-07 11:08:24,716 E CatalogueDatabase    },
2016-06-07 11:08:24,716 E CatalogueDatabase    "protocolCapabilities" {
2016-06-07 11:08:24,716 E CatalogueDatabase    "http": true
2016-06-07 11:08:24,716 E CatalogueDatabase  }
2016-06-07 11:08:24,716 E CatalogueDatabase  }
```

This won't solve the problem, but at least it will print the file, so we can see why it fails.

**Comment by emmelmann-fokus** [comment]
The images should be ready.  The latest update causing a build finished 27 minutes ago.  You may check yourself in cause you're in doubt if the latest update is available:

https://hub.docker.com/r/rethink/catalogue-broker/builds/
https://hub.docker.com/r/rethink/catalogue-database/builds/

Cheers,

Marc

**Comment by Endebert** [comment]
@vitormsilva I was able to reproduce the error by modifying the descritption.json. In the current version, it would look like this:
```
2016-06-07 11:43:55,141 E CatalogueDatabase  Parsing ./catalogue_objects/runtime/Runtime/description.json failed!
 com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected name at line 23 column 2 path $.protocolCapabilities
	at com.google.gson.internal.Streams.parse(Streams.java:60) ~[rethink-catalogue-database-1.1.0-jar-with-dependencies.jar:?]
	at com.google.gson.JsonParser.parse(JsonParser.java:84) ~[rethink-catalogue-database-1.1.0-jar-with-dependencies.jar:?]
	at com.google.gson.JsonParser.parse(JsonParser.java:59) ~[rethink-catalogue-database-1.1.0-jar-with-dependencies.jar:?]
	at eu.rethink.catalogue.database.CatalogueDatabase.parseJson(CatalogueDatabase.java:386) ~[rethink-catalogue-database-1.1.0-jar-with-dependencies.jar:?]
	at eu.rethink.catalogue.database.CatalogueDatabase.parseObjects(CatalogueDatabase.java:421) [rethink-catalogue-database-1.1.0-jar-with-dependencies.jar:?]
	at eu.rethink.catalogue.database.CatalogueDatabase.start(CatalogueDatabase.java:318) [rethink-catalogue-database-1.1.0-jar-with-dependencies.jar:?]
	at eu.rethink.catalogue.database.CatalogueDatabase.main(CatalogueDatabase.java:267) [rethink-catalogue-database-1.1.0-jar-with-dependencies.jar:?]
Caused by: com.google.gson.stream.MalformedJsonException: Expected name at line 23 column 2 path $.protocolCapabilities
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1567) ~[rethink-catalogue-database-1.1.0-jar-with-dependencies.jar:?]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:509) ~[rethink-catalogue-database-1.1.0-jar-with-dependencies.jar:?]
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:418) ~[rethink-catalogue-database-1.1.0-jar-with-dependencies.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:742) ~[rethink-catalogue-database-1.1.0-jar-with-dependencies.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:718) ~[rethink-catalogue-database-1.1.0-jar-with-dependencies.jar:?]
	at com.google.gson.internal.Streams.parse(Streams.java:48) ~[rethink-catalogue-database-1.1.0-jar-with-dependencies.jar:?]
	... 6 more
2016-06-07 11:43:55,144 E CatalogueDatabase  Contents of file ./catalogue_objects/runtime/Runtime/description.json:
2016-06-07 11:43:55,144 E CatalogueDatabase  {
2016-06-07 11:43:55,144 E CatalogueDatabase    "cguid": "30002",
2016-06-07 11:43:55,144 E CatalogueDatabase    "runtimeType": "browser",
2016-06-07 11:43:55,144 E CatalogueDatabase    "version": "1.0",
2016-06-07 11:43:55,144 E CatalogueDatabase    "objectName": "Runtime",
2016-06-07 11:43:55,144 E CatalogueDatabase    "description": "This is a hyperty runtime descriptor",
2016-06-07 11:43:55,144 E CatalogueDatabase    "language": "Javascript ECMA6",
2016-06-07 11:43:55,144 E CatalogueDatabase    "hypertyCapabilities": {
2016-06-07 11:43:55,144 E CatalogueDatabase      "mic": true,
2016-06-07 11:43:55,145 E CatalogueDatabase      "camera": true,
2016-06-07 11:43:55,145 E CatalogueDatabase      "sensor": false,
2016-06-07 11:43:55,145 E CatalogueDatabase      "webrtc": true,
2016-06-07 11:43:55,145 E CatalogueDatabase      "ortc": true
2016-06-07 11:43:55,145 E CatalogueDatabase    },
2016-06-07 11:43:55,145 E CatalogueDatabase    "protocolCapabilities": {
2016-06-07 11:43:55,145 E CatalogueDatabase      "http": true,
2016-06-07 11:43:55,145 E CatalogueDatabase      "https": true,
2016-06-07 11:43:55,145 E CatalogueDatabase      "ws": true,
2016-06-07 11:43:55,145 E CatalogueDatabase      "wss": true,
2016-06-07 11:43:55,145 E CatalogueDatabase      "coap": false,
2016-06-07 11:43:55,145 E CatalogueDatabase      "datachannel": false
2016-06-07 11:43:55,145 E CatalogueDatabase    },
2016-06-07 11:43:55,145 E CatalogueDatabase  }
```
I'm pretty sure the reason for the error is one too many commas in the file, specifically a comma after the `protocolCapabilities` object.

After checking the git history of description.json, I can see that [you even fixed that error yourself 4 days ago](https://github.com/reTHINK-project/dev-catalogue/commit/68fcc84488c4a0c75545c45ad576929f49cd00e2). I guess you are just not using the most recent version.

**Comment by Endebert** [comment]
No response, so I guess this is can be closed
